# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Ejemplo
                                 A QGIS plugin
 Ejemplo de complemento
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-08-29
        copyright            : (C) 2023 by valen
        email                : valetobares11@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Ejemplo class from file Ejemplo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ejemplo import Ejemplo
    return Ejemplo(iface)
