# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EmergencyDispatcher
                                 A QGIS plugin
 EmergencyDispatcher
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-26
        copyright            : (C) 2024 by Alvarez Yanina, Gaspero Maximiliano, Tobares Valentin
        email                : yanialva2009@gmail.com, maxigaspero@gmail.com, valetobares11@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EmergencyDispatcher class from file EmergencyDispatcher.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .EmergencyDispatcher import EmergencyDispatcher
    return EmergencyDispatcher(iface)
